// This file is auto-generated by TanStack Router.
// Do not edit it manually as it will be overwritten.

import { createFileRoute, createRootRoute } from '@tanstack/react-router'

// Import route components
import RootComponent from './routes/__root'
import IndexComponent from './routes/index'
import DashboardComponent from './routes/dashboard'

// Create file routes
const rootRoute = createRootRoute({
  component: RootComponent,
})

const indexRoute = createFileRoute('/')({
  component: IndexComponent,
})

const dashboardRoute = createFileRoute('/dashboard')({
  component: DashboardComponent,
})

// Build route tree
export const routeTree = rootRoute.addChildren([
  indexRoute,
  dashboardRoute,
])